### ISSUE TITLE
Upgrade 0.9.9 to 1.1.0 failures

### ISSUE THREAD

**Issue by MrHelga** [Maprunner/rg2#244]
I have a working RG2 installation with 0.9.9. When I update the files with version 1.1.0, I encounter 2 issues:
1) the events don't load anymore; instead it stays frozen with "Saving courses"
2) maybe related: in an empty 1.1.0 installation I'm not able to create a new event and load the Ocad XML course file (IOFVersion version="2.0.3") : "Data missing: No course information. Check your course XML file. Please enter all necessary information before creating the event."

**Comment by Maprunner** [comment]
Please can you give me a link to your installation so that I can have a look.

**Comment by MrHelga** [comment]
Hi Simon,

http://www.hock.be/routegadget/rg2/ is the site with version 1.1.0 and 
the /kartat data from 0.9.9
Thanks!

**Comment by Maprunner** [comment]
I left a file out of the minified version. This is corrected in version 1.1.1.

**Comment by MrHelga** [comment]
Many thanks!
