### ISSUE TITLE
Missing splits in 1.1.4

### ISSUE THREAD

**Issue by MrHelga** [Maprunner/rg2#259]
I uploaded a results CSV file with version 1.1.4, and all controls except the first and finish were missing:
32|2|2|H40 Michael HOCK|0|__H40 Michael HOCK_##ok||00:48:58|386;2938
Uploaded the same file with 1.1.1 and it was correct:
32|2|2|H40 Michael HOCK|0|__H40 Michael HOCK_##ok||00:48:58|386;457;590;716;1106;1180;1513;1788;2048;2213;2301;2673;2771;2913;2938

The CSV is:
35;;;H40 Michael HOCK;;;;;;;;00:48:58;;;;ARDOC;;;02;;;;;;;;;;;;;;;;;;;;;2;5470;195;14;;588:08;;179;00:06:26;181;00:07:37;180;00:09:50;183;00:11:56;161;00:18:26;165;00:19:40;150;00:25:13;149;00:29:48;155;00:34:08;147;00:36:53;148;00:38:21;139;00:44:33;143;00:46:11;175;00:48:33

Thanks!

**Comment by Maprunner** [comment]
RG2 looks at the header of the csv file to determine where each required field is. Please can you post the first line of the file so I can see what is going on.

**Comment by MrHelga** [comment]
This is the header I have always used for RG2 and for SplitsBrowser (for ages).
Stno;;;Surname
Now I remember that I had to ADD 2 additional ;; in the data part after the surname to make it work with RG2 1.1.1 and earlier. Maybe you have reworked this area to make it compatible with the standard SICSV?
Would it be possible to keep on supporting "your" 1.1.1 version of the CSV file?
Thanks.

**Comment by MrHelga** [comment]
Could you please post your expected header line? Then I will simply adjust my software's export accordingly... Thanks!

**Comment by Maprunner** [comment]
RG2 reads the first line of a CSV file and tries to find all the necessary fields. Your CSV file must as a minimum have columns with the following names: 'Database Id', 'Surname', 'First name', 'Start', 'Time', 'Classifier', 'City' OR 'Club', 'Short' (which is the Class name), 'Course', 'Course controls', 'Place' OR 'Pl', 'Start punch', 'Control1', 'Punch1', 'Control2'. Sportident CSV files, or any other CSV file that meets the [BOF results file requirements] (http://www.britishorienteering.org.uk/images/uploaded/downloads/events_results_submission_file_specification.pdf) should work. RG2 will automatically detect if you are using commas or semicolons as the separator. If you are using Autodownload then you need to generate the file using the "Export OE splits" option.

**Comment by MrHelga** [comment]
Thank you, the full header helps!
