### ISSUE TITLE
Javascript doesn't run - Firefox and Chrome

### ISSUE THREAD

**Issue by juliapaul** [Maprunner/rg2#260]
(for Norfolk OC).  I normally use Chrome, successfully, to upload events to Routegadget2.  This time it just aborts when I need to adjust the controls to fit the map.  I get the jigsaw symbol and more info tells me javascript is not enabld.  I have checked and it IS enabled.  Tried adding routegadget to the exception list, no difference.

Tried in Firefox with similar result - it asks if I want it to run, I click Yes, but it still aborts.

Done various googling and other tests, eg  Firefox about:config returns "javascript.enabled;true" 

Now stuck.  (PC, Windows 8.1)

**Comment by Maprunner** [comment]
The problem you are having is with Java and the old Routegadget manager. Java and javascript are different things, but the names cause endless confusion.

One of the main reasons for creating RG2 was to avoid Java. The situation has now got so bad that Java is essentially unusable for most people.

I recommend that you move to the RG2 manager. The [wiki page] (https://github.com/Maprunner/rg2/wiki/Manager-details) has more details, and there is also a [short video] (http://screencast-o-matic.com/u/VJsd/RG2-Cassiobury-Manager-Demo) that should be helpful. I have reset the NOR account so you should be able to use your existing user name and password to log in.

**Comment by juliapaul** [comment]
Thank you Simon.  I took over about 6 months ago and thought I was given all the details for RG2.  Obviously I wasn't.  I can already see some nice enhancements.

Regards

Julia Paul

-----Original Message-----

**Comment by juliapaul** [comment]
FABULOUS thank you.

Julia for Norfolk OC


-----Original Message-----

**Comment by Maprunner** [comment]
No change needed so close.
