### ISSUE TITLE
multiple classes per cource

### ISSUE THREAD

**Issue by okvittem** [Maprunner/rg2#273]
The Brikkesys result system produce IOF XML results per class and there
are many classes per cource. 
Would it be feasible to support mapping  multiple classes per cource ?

**Comment by Maprunner** [comment]
Can you send me an example of the XML file? It should be possible, but it might make the user interface a bit more complicated since you will need to select which option you want.

**Comment by okvittem** [comment]
On 20. mai 2015 20:43, Simon Errington wrote:
>
> Can you send me an example of the XML file? It should be possible, but 
> it might make the user interface a bit more complicated since you will 
> need to select which option you want.
>
Hi Simon,

RG1 lists classes and each has a select menu for courses.
I am pursuing a parallel effort on this problem to try to produce 
results by course also
in Brikkesys. That is my preferred solution.

The problem at the moment is that newer ocad delvers IOF xml 3.0 by default
and  that is not supported by RG1. RG2 works, but with only one class 
per course.
Course planners tend to overlook these options.
http://brikkesys.no/iof-results30.php%3fid=1572

cheers
   Olav

**Comment by McNobody** [comment]
Hi Simon!

I'm interested this feature too.

We had national competion with multiple classes per courses.  We had classes for D10, D12, D14, D16, D18, D21, D40, D50, D60, H10, H12, H14, H16, H18, H21, H40, H50, H60, H70, H80. There was totally eight courses. It would be really great to choose a course for every class.

Our normal weekly orienteering events have only one class per one course. The current UI is working well for those weekly events.

**Comment by McNobody** [comment]
Actually that was quite easy atleast for IOX XML 2.0.3. There is a attached patch for courseparser.js. There is one or more ClassShortName elements inside Course.

Additionally this patch sort courses by the name of the course.

[courseparser.js.txt](https://github.com/Maprunner/rg2/files/343796/courseparser.js.txt)
