### ISSUE TITLE
Events get multiplied when selecting another language

### ISSUE THREAD

**Issue by MrHelga** [Maprunner/rg2#274]
Version 1.1.5
When you open the language selection box, the events get multiplied in the first tab.
![unbenannt](https://cloud.githubusercontent.com/assets/7961822/8302759/48605388-1999-11e5-80eb-a89b68f62159.PNG)

**Comment by MrHelga** [comment]
I'm so sorry, but I made the change in  js/rg2ui.js and it's still the same problem. Is that not enough, or do I need to wait for the next release? Thanks!

**Comment by Maprunner** [comment]
That should be enough. I could recreate the problem on my system, and this change fixed it. 

RG2 loads a minified version of all the js files, so it won't pick up a local edit unless you force it to use the uncompressed version by adding ?debug to the url. For now you could just update your rg2all.min.js file from github to get all the changes for version 1.1.7.

**Comment by MrHelga** [comment]
Thanks! The ?debug trick did it!
