### ISSUE TITLE
Autofit GPS tracks

### ISSUE THREAD

**Issue by Maprunner** [Maprunner/rg2#279]
A popular request, and it turns out to be more straightforward than I thought. Possibly need to allow user to set time offset, although the initial implementation guesses within 10 seconds either side of the split time, based on average running speed.

I should really disable it for georeferenced maps, but people will only complain.

**Comment by apford** [comment]
I have just started using rg2 and added my GPS track for Day2 S6D course 21.
As it was slightly off, most notably at the finish I tried autofit, which I now realise was wrong. 
Would it be possible to add an undo button for autofit ?
(and can the bad fit be deleted ?)

**Comment by Maprunner** [comment]
Turns out it isn't working properly for score events, so route disappears when you click autofit. Course info not being correctly saved when initialising the course.
