### ISSUE TITLE
Reset button on draw tab doesn't work properly

### ISSUE THREAD

**Issue by JamesErrington** [Maprunner/rg2#288]
It doesn't reset the course dropdown, but locks out the name dropdown so one has to pick another course then pick the right course again to re-select one's name.

It seems to be a conflict in what the button is actually there for: is it to reset the drawn course, or to reset the entry of a runner all together?

**Comment by JamesErrington** [comment]
Easy enough fix to make it completely reset the draw tab, depends if this is expected behaviour

**Comment by Maprunner** [comment]
Probably best to reset everything. Add a call to reset course dropdown as part of reset.
