### ISSUE TITLE
Ignore controls that the competitor has not visited (i.e in the case of 'missed post')

### ISSUE THREAD

**Issue by hansonwj** [Maprunner/rg2#294]
Currently, if a competitor misses controls, or retires, they are still required to click on the controls as though they have visited them, when drawing their route. 

It would be useful if the application could check which controls the competitor has visited, and only require them to draw those legs.

Thank you

**Comment by JamesErrington** [comment]
Due to legacy compatibility, it is unlikely this can be implemented any time soon and is therefore of low priority
