### ISSUE TITLE
Deleting Erroneous GPS Tracks

### ISSUE THREAD

**Issue by callmetom** [Maprunner/rg2#295]
Morning,

Today marks my first day as a user of Route Gadget 2 and I've foolishly uploaded a track to http://www.noroc.routegadget.co.uk/rg2/#77, not fitted it and then apparently saved it. Is there a way to delete tracks that I've uploaded in error? I can't seem to get rid of the GPS track and it's wildly off the edge of the map.

I've worked out where I went wrong and have uploaded a second 'fitted' track. 

Regards,

Tom

**Comment by paul-frost** [comment]
Normally this needs to be done by the administrator of that clubs RG account, but you are in luck as I had the password and have deleted your old route.

**Comment by callmetom** [comment]
Thanks for bailing me out Paul. 

I'm fairly new to this orienteering malarky but I'm keen to get my head around tools such as RG - I can't believe that tools that can provide such great post-race analysis are free!
