### ISSUE TITLE
Add shareable link to course and track

### ISSUE THREAD

**Issue by JamesErrington** [Maprunner/rg2#353]
Could be through Twitter + Facebook integration but more flexible would be Routegadget link shortener (routegadg.et?) that would be accessed via share button probably next to delete icon (though need to think about mobile + tablet users - maybe confirmation before deletion)

**Comment by JamesErrington** [comment]
Current thinking is to add Twitter and Facebook ribbons that would share the current page - so any routes and courses up would be shared

**Comment by Maprunner** [comment]
First attampt include in version 1.4.3. Close here for now and open new issues for future updates.
