### ISSUE TITLE
saving routes when mispunched

### ISSUE THREAD

**Issue by nstjhp** [Maprunner/rg2#365]
Is it possible to enable the save button to work even if you didn't go to all the controls?

I just drew the route I actually took but then found I couldn't save it which was quite frustrating.

**Comment by JamesErrington** [comment]
This has been discussed before and though we can see it's usefulness, it is not currently something we are looking at adding

see #294

**Comment by nstjhp** [comment]
Ah OK fair enough. 

Please keep up the good work.

**Comment by Maprunner** [comment]
IN the end I foudn a way of doing this which I think will work OK. It has been implemented in version 1.4.2 which has now been rolled out so we'll see what happens.
