### ISSUE TITLE
Adjust GPS tracks to start time

### ISSUE THREAD

**Issue by okvittem** [Maprunner/rg2#371]
Hi Simon,
Would i be feasible to adjust the the start point of GPS tracks by the start time when doing animation ?
The results xml file contain <FinishTime> and <Time>

Cheers
  Olav

**Comment by JamesErrington** [comment]
Hi,

Sorry, but there are currently no plans to add GPS track editing of this kind to RG2; outside GPS editing tools should be used to adjust tracks before uploading to RG2.

James
