### ISSUE TITLE
Login manage

### ISSUE THREAD

**Issue by rgomme** [Maprunner/rg2#381]
Hello,

I installed RG2 on my server, I followed the installation instructions, but I can not connect to the manager.
I always have the same message "login failed".
I also followed the instructions "Security" by deleting the file "rg2userinfo.txt". I have to start the login procedure again, but still "Login Failed"

Is it possible to get help?

Thank you

http://liguenouvelleaquitaine-co.fr/gadget2016/rg2

![sans-titre-2](https://user-images.githubusercontent.com/30016353/27992185-dd4cc314-648d-11e7-8989-b0ddedd5b43d.jpg)

![rg2-config](https://user-images.githubusercontent.com/30016353/27992203-98e262d2-648e-11e7-8303-b481fe1713d9.PNG)

**Comment by Maprunner** [comment]
This is probably to do with http and https configurations. Your config file uses https for RG_BASE_DIRECTORY.

If you access your site at http://liguenouvelleaquitaine-co.fr/gadget2016/rg2/ you get an "Events request failed" message and the console reports an XMLHttpRequest error.

If you access your site at https://liguenouvelleaquitaine-co.fr/gadget2016/rg2/  it works correctly.

So you need to make sure that all requests go via https. You can add it in the URL in the browser as above.

The better solution is to configure your .htaccess file (assuming you are on Apache) to force all http requests to be rewritten to https.  Try a Google search on "force http to https" if you need help.

**Comment by rgomme** [comment]
Good evening,
Thank you
It works in https, i will modify the .htacces

Thank you
