### ISSUE TITLE
Draw function bug?

### ISSUE THREAD

**Issue by BeefFrank** [Maprunner/rg2#392]
Just installed rg2 v1.4.3 and v1.4.4 and, with both, draw function appears to stop at cp2 (red highlight moves from cp1 to cp2 but remains there and won't update to cp3 and beyond), so cannot proceed to finish and thus save a drawn route. Draw works OK in rg2 v1.4.0.

**Comment by Maprunner** [comment]
Can you provide a link to the relevant site and event?

**Comment by BeefFrank** [comment]
I replied by email but looks like it went to a general address.
I installed an example of v1.4.3 at http://www.limousinmusclealliance.com.au/routegadget2.1.4.3/rg2/#1. The website is an expired website that I've used as a test installation. Only one event has been loaded. If you go to the draw tab, you can select any competitor to try drawing a route. Route drawing to cp1 seems OK. The route snaps to cp1 when it gets close, and cp2 goes red. Subsequent drawing will then not snap to cp2 when the route gets close, although if you have the "align map to next control" box ticked the map re-aligns correctly. Cp2 remains red and the map aligned with cp2/cp3 regardless of how close the route gets to cp3.
An example of v1.4.0, which appears to work OK in draw mode, is at www.limousinmusclealliance.com.au/routegadget2.1.4.0/rg2/#1.
Both installations have identical kartat directories.
