### ISSUE TITLE
add event panel with misaligned fields

### ISSUE THREAD

**Issue by okvittem** [Maprunner/rg2#399]
The Map selector appears on the next line after the 'Map' header in the Add event panel 
and the following lines is accordingly off by one line. 

This is latest Firefox on Linux 55.0.2. The alignment is fine in Chrome.
RG2 is the latest from github.

![image](https://user-images.githubusercontent.com/3093300/31049422-d6573ef4-a632-11e7-8b16-03a458f69437.png)

**Comment by dg0yt** [comment]
~~~
<div id="rg2-manager-map-select">
  <span>Map:<select class="pushright manage-input" id="rg2-map-selected"></select></span>
</div>
~~~

There are two issues here:
- There seems to be an inappropriate mix of inline and block features here: label and input field are put in a `span` (inline), but the input field is marked `float:right` (via CSS class `pushright`) -- which is a block feature AFAIU. 
- There is no clearing of the floats. If they wouldn't be more than 50% wide, they could as well end up placed side by side. 
  This issue can be solved in the rg2 .css file by implementing a clearfix solution as used in [Bootstrap](https://getbootstrap.com/docs/4.1/utilities/clearfix/):
  ~~~
  #rg2-manage-create > div::after {
    display: block;
    content: "";
    clear: both;
  }

**Comment by okvittem** [comment]
On 17. juli 2018 08:32, Kai Pastor wrote:
> |<div id="rg2-manager-map-select"> <span>Map:<select class="pushright
> manage-input" id="rg2-map-selected"></select></span> </div> |
>
> There are two issues here:
>
>   * There seems to be an inappropriate mix of inline and block
>     features here: label and input field are put in a |span| (inline),
>     but the input field is marked |float:right| (via CSS class
>     |pushright|) -- which is a block feature AFAIU.
>   * There is no clearing of the floats. If they wouldn't be more than
>     50% wide, they could as well end up placed side by side.
>     This issue can be solved in the rg2 .css file by implementing a
>     clearfix solution as used in Bootstrap
>     <https://getbootstrap.com/docs/4.1/utilities/clearfix/>:
>     |#rg2-manage-create > div::after { display: block; content: "";
>     clear: both; }|
>
Hi,
Thanks for fixing up :
|I appended  this to  css/rg2.css
- it looks OK in Chromium and Vivaldi with Map selector being in line
with the Map: lead text,
but not in Firefox.

cheers
  Olav
|

**Comment by dg0yt** [comment]
For an installed rg2, you need to modify rg2-1.4.8.min.css (or whatever version is loaded in the version you installed).
