### ISSUE TITLE
JK routegadget is broken

### ISSUE THREAD

**Issue by mpickering** [Maprunner/rg2#434]
It seems that recently all the routegadget urls started using https. However something seemed to go wrong in the deployment of the JK site as it still tries to load the resources by http.

If you load the site then the CSS and javascript will fail to load.

https://www.jk.routegadget.co.uk/rg2/

The errors point to the mismatched protocol.

```
(index):17 Mixed Content: The page at 'https://www.jk.routegadget.co.uk/rg2/' was loaded over HTTPS, but requested an insecure stylesheet 'http://www.routegadget.co.uk/rg2/css/rg2-1.5.2.min.css'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by Maprunner** [comment]
http instead of https in config file, now fixed. I have been migrating to all routegadget.co.uk sites to https but it is a manual process for various reasons. Managed to update the other config files OK, but updated the old version rather than the live version for jk.
