### ISSUE TITLE
NGOC routegadget is broken?

### ISSUE THREAD

**Issue by mpickering** [Maprunner/rg2#436]
It seems that the NGOC routegadget page is broken and won't load any events.

https://ngoc.routegadget.co.uk/rg2/

The error is "Events request failed"

The error in the console is:

```
Failed to load https://www.ngoc.routegadget.co.uk/rg2/rg2api.php?type=events&cache=false&_=1541245931675: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://ngoc.routegadget.co.uk' is therefore not allowed access.
```

I tried on both Chrome and Safari and tried clearing the cache.

**Comment by Maprunner** [comment]
All subdirectory .htaccess files now removed so everything should now be going through the same top-level routing. This now:

- forces https
- adds www if missing (which is what caused this issue)
- redirects reitti.cgi to rg2
