### ISSUE TITLE
Problems with new installation on own server

### ISSUE THREAD

**Issue by Tschoppenhof** [Maprunner/rg2#442]
I installed the files as instructed in the guide. It runs and I can add maps, draw courses and add events. The problem is that the event and map name aren't saved, they just stay empty even if I update the event.
My installation is at http://www.ol-db.one/routegadget/rg2. Thanks for any hint and your great work.

**Comment by Maprunner** [comment]
I seem to remember a similar problem that turned out to be associated with encoding. Try adding the following to your rg2-config.php file
  
```
define('RG_INPUT_ENCODING', 'UTF-8');
```
I need to add this as a default in rg2api.php if this turns out to be the problem.

**Comment by Tschoppenhof** [comment]
That was it, it works now. Thanks a lot.
Maybe it a hint in the installation guide would also be helpful.
