### ISSUE TITLE
GPS Routes Offset

### ISSUE THREAD

**Issue by hansonwj** [Maprunner/rg2#476]
Hi Simon,

With the New Zealand RG2 we are encountering an issue where some GPS routes uploaded to RG2 appear offset from the position they were originally loaded. 

The following routes are a good example:  (http://rg.orienteering.org.nz/gadget/rg2/#778&course=2&route=50015,50024)

I will note that we are running RG and RG2 side-by-side, and that the 'original' routegadget appears to be displaying the correct locations for the GPS routes for all runners: (http://rg.orienteering.org.nz/gadget/cgi-bin/reitti.cgi?act=map&id=778)

Any ideas why this display issue is occurring?

Thanks - Jake

**Comment by Maprunner** [comment]
Finally managed to track this down. The old Routegadget used integers for routes. The new version has changed to use one decimal place.  All the extra decimal places gradually added up to produce an offset in the route, so the further you go the more the offset is.

There is a very simple correction which I have built into Release 1.6.1 which should be available later today.
