### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by DACN** [Maprunner/rg2#477]
PHP 5 or PHP 7 or either?

Can't see any comments in the installation instructions.

**Comment by Maprunner** [comment]
I'd recommend 7. It will probably work on PHP 5 since the PHP doesn't do anything clever, but it definitely works on 7.

**Comment by DACN** [comment]
thanks

(old server which is being replaced came with PHP5; so yes maprunner does run on PHP5 - checking that PHP7 is supported when server is rebuilt)
